import Mathesis.Basic
theorem bench_t0 : MTrue := MTrue.intro
theorem bench_t1 : MAnd MTrue MTrue := MAnd.intro MTrue.intro MTrue.intro
theorem bench_t2 : MOr MTrue MTrue := MOr.inl MTrue.intro
theorem bench_t3 : MAnd MTrue (MOr MTrue MTrue) := MAnd.intro MTrue.intro (MOr.inl MTrue.intro)
theorem bench_t4 : MOr (MAnd MTrue MTrue) MTrue := MOr.inl (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t5 : MAnd (MOr MTrue MTrue) (MAnd MTrue MTrue) := MAnd.intro (MOr.inl MTrue.intro) (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t6 : MTrue := MTrue.intro
theorem bench_t7 : MAnd MTrue MTrue := MAnd.intro MTrue.intro MTrue.intro
theorem bench_t8 : MOr MTrue MTrue := MOr.inl MTrue.intro
theorem bench_t9 : MAnd MTrue (MOr MTrue MTrue) := by exact MAnd.intro MTrue.intro (MOr.inl MTrue.intro)
theorem bench_t10 : MOr (MAnd MTrue MTrue) MTrue := MOr.inl (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t11 : MAnd (MOr MTrue MTrue) (MAnd MTrue MTrue) := MAnd.intro (MOr.inl MTrue.intro) (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t12 : MTrue := MTrue.intro
theorem bench_t13 : MAnd MTrue MTrue := MAnd.intro MTrue.intro MTrue.intro
theorem bench_t14 : MOr MTrue MTrue := MOr.inl MTrue.intro
theorem bench_t15 : MAnd MTrue (MOr MTrue MTrue) := MAnd.intro MTrue.intro (MOr.inl MTrue.intro)
theorem bench_t16 : MOr (MAnd MTrue MTrue) MTrue := MOr.inl (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t17 : MAnd (MOr MTrue MTrue) (MAnd MTrue MTrue) := MAnd.intro (MOr.inl MTrue.intro) (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t18 : MTrue := MTrue.intro
theorem bench_t19 : MAnd MTrue MTrue := by exact MAnd.intro MTrue.intro MTrue.intro
theorem bench_t20 : MOr MTrue MTrue := MOr.inl MTrue.intro
theorem bench_t21 : MAnd MTrue (MOr MTrue MTrue) := MAnd.intro MTrue.intro (MOr.inl MTrue.intro)
theorem bench_t22 : MOr (MAnd MTrue MTrue) MTrue := MOr.inl (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t23 : MAnd (MOr MTrue MTrue) (MAnd MTrue MTrue) := MAnd.intro (MOr.inl MTrue.intro) (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t24 : MTrue := MTrue.intro
theorem bench_t25 : MAnd MTrue MTrue := MAnd.intro MTrue.intro MTrue.intro
theorem bench_t26 : MOr MTrue MTrue := MOr.inl MTrue.intro
theorem bench_t27 : MAnd MTrue (MOr MTrue MTrue) := MAnd.intro MTrue.intro (MOr.inl MTrue.intro)
theorem bench_t28 : MOr (MAnd MTrue MTrue) MTrue := MOr.inl (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t29 : MAnd (MOr MTrue MTrue) (MAnd MTrue MTrue) := by exact MAnd.intro (MOr.inl MTrue.intro) (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t30 : MTrue := MTrue.intro
theorem bench_t31 : MAnd MTrue MTrue := MAnd.intro MTrue.intro MTrue.intro
theorem bench_t32 : MOr MTrue MTrue := MOr.inl MTrue.intro
theorem bench_t33 : MAnd MTrue (MOr MTrue MTrue) := MAnd.intro MTrue.intro (MOr.inl MTrue.intro)
theorem bench_t34 : MOr (MAnd MTrue MTrue) MTrue := MOr.inl (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t35 : MAnd (MOr MTrue MTrue) (MAnd MTrue MTrue) := MAnd.intro (MOr.inl MTrue.intro) (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t36 : MTrue := MTrue.intro
theorem bench_t37 : MAnd MTrue MTrue := MAnd.intro MTrue.intro MTrue.intro
theorem bench_t38 : MOr MTrue MTrue := MOr.inl MTrue.intro
theorem bench_t39 : MAnd MTrue (MOr MTrue MTrue) := by exact MAnd.intro MTrue.intro (MOr.inl MTrue.intro)
theorem bench_t40 : MOr (MAnd MTrue MTrue) MTrue := MOr.inl (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t41 : MAnd (MOr MTrue MTrue) (MAnd MTrue MTrue) := MAnd.intro (MOr.inl MTrue.intro) (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t42 : MTrue := MTrue.intro
theorem bench_t43 : MAnd MTrue MTrue := MAnd.intro MTrue.intro MTrue.intro
theorem bench_t44 : MOr MTrue MTrue := MOr.inl MTrue.intro
theorem bench_t45 : MAnd MTrue (MOr MTrue MTrue) := MAnd.intro MTrue.intro (MOr.inl MTrue.intro)
theorem bench_t46 : MOr (MAnd MTrue MTrue) MTrue := MOr.inl (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t47 : MAnd (MOr MTrue MTrue) (MAnd MTrue MTrue) := MAnd.intro (MOr.inl MTrue.intro) (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t48 : MTrue := MTrue.intro
theorem bench_t49 : MAnd MTrue MTrue := by exact MAnd.intro MTrue.intro MTrue.intro
theorem bench_t50 : MOr MTrue MTrue := MOr.inl MTrue.intro
theorem bench_t51 : MAnd MTrue (MOr MTrue MTrue) := MAnd.intro MTrue.intro (MOr.inl MTrue.intro)
theorem bench_t52 : MOr (MAnd MTrue MTrue) MTrue := MOr.inl (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t53 : MAnd (MOr MTrue MTrue) (MAnd MTrue MTrue) := MAnd.intro (MOr.inl MTrue.intro) (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t54 : MTrue := MTrue.intro
theorem bench_t55 : MAnd MTrue MTrue := MAnd.intro MTrue.intro MTrue.intro
theorem bench_t56 : MOr MTrue MTrue := MOr.inl MTrue.intro
theorem bench_t57 : MAnd MTrue (MOr MTrue MTrue) := MAnd.intro MTrue.intro (MOr.inl MTrue.intro)
theorem bench_t58 : MOr (MAnd MTrue MTrue) MTrue := MOr.inl (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t59 : MAnd (MOr MTrue MTrue) (MAnd MTrue MTrue) := by exact MAnd.intro (MOr.inl MTrue.intro) (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t60 : MTrue := MTrue.intro
theorem bench_t61 : MAnd MTrue MTrue := MAnd.intro MTrue.intro MTrue.intro
theorem bench_t62 : MOr MTrue MTrue := MOr.inl MTrue.intro
theorem bench_t63 : MAnd MTrue (MOr MTrue MTrue) := MAnd.intro MTrue.intro (MOr.inl MTrue.intro)
theorem bench_t64 : MOr (MAnd MTrue MTrue) MTrue := MOr.inl (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t65 : MAnd (MOr MTrue MTrue) (MAnd MTrue MTrue) := MAnd.intro (MOr.inl MTrue.intro) (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t66 : MTrue := MTrue.intro
theorem bench_t67 : MAnd MTrue MTrue := MAnd.intro MTrue.intro MTrue.intro
theorem bench_t68 : MOr MTrue MTrue := MOr.inl MTrue.intro
theorem bench_t69 : MAnd MTrue (MOr MTrue MTrue) := by exact MAnd.intro MTrue.intro (MOr.inl MTrue.intro)
theorem bench_t70 : MOr (MAnd MTrue MTrue) MTrue := MOr.inl (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t71 : MAnd (MOr MTrue MTrue) (MAnd MTrue MTrue) := MAnd.intro (MOr.inl MTrue.intro) (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t72 : MTrue := MTrue.intro
theorem bench_t73 : MAnd MTrue MTrue := MAnd.intro MTrue.intro MTrue.intro
theorem bench_t74 : MOr MTrue MTrue := MOr.inl MTrue.intro
theorem bench_t75 : MAnd MTrue (MOr MTrue MTrue) := MAnd.intro MTrue.intro (MOr.inl MTrue.intro)
theorem bench_t76 : MOr (MAnd MTrue MTrue) MTrue := MOr.inl (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t77 : MAnd (MOr MTrue MTrue) (MAnd MTrue MTrue) := MAnd.intro (MOr.inl MTrue.intro) (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t78 : MTrue := MTrue.intro
theorem bench_t79 : MAnd MTrue MTrue := by exact MAnd.intro MTrue.intro MTrue.intro
theorem bench_t80 : MOr MTrue MTrue := MOr.inl MTrue.intro
theorem bench_t81 : MAnd MTrue (MOr MTrue MTrue) := MAnd.intro MTrue.intro (MOr.inl MTrue.intro)
theorem bench_t82 : MOr (MAnd MTrue MTrue) MTrue := MOr.inl (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t83 : MAnd (MOr MTrue MTrue) (MAnd MTrue MTrue) := MAnd.intro (MOr.inl MTrue.intro) (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t84 : MTrue := MTrue.intro
theorem bench_t85 : MAnd MTrue MTrue := MAnd.intro MTrue.intro MTrue.intro
theorem bench_t86 : MOr MTrue MTrue := MOr.inl MTrue.intro
theorem bench_t87 : MAnd MTrue (MOr MTrue MTrue) := MAnd.intro MTrue.intro (MOr.inl MTrue.intro)
theorem bench_t88 : MOr (MAnd MTrue MTrue) MTrue := MOr.inl (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t89 : MAnd (MOr MTrue MTrue) (MAnd MTrue MTrue) := by exact MAnd.intro (MOr.inl MTrue.intro) (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t90 : MTrue := MTrue.intro
theorem bench_t91 : MAnd MTrue MTrue := MAnd.intro MTrue.intro MTrue.intro
theorem bench_t92 : MOr MTrue MTrue := MOr.inl MTrue.intro
theorem bench_t93 : MAnd MTrue (MOr MTrue MTrue) := MAnd.intro MTrue.intro (MOr.inl MTrue.intro)
theorem bench_t94 : MOr (MAnd MTrue MTrue) MTrue := MOr.inl (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t95 : MAnd (MOr MTrue MTrue) (MAnd MTrue MTrue) := MAnd.intro (MOr.inl MTrue.intro) (MAnd.intro MTrue.intro MTrue.intro)
theorem bench_t96 : MTrue := MTrue.intro
theorem bench_t97 : MAnd MTrue MTrue := MAnd.intro MTrue.intro MTrue.intro
theorem bench_t98 : MOr MTrue MTrue := MOr.inl MTrue.intro
theorem bench_t99 : MAnd MTrue (MOr MTrue MTrue) := by exact MAnd.intro MTrue.intro (MOr.inl MTrue.intro)
